name: Tri Sell
favicon: null
layout_spectrum: 0.32653737533837557
typography_spectrum: 0.620186016894877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.607702974928543
  lightness: 0.6116684412118047
  saturation: 0.10239390237256885
  rhythmicContrast: 0.07860043970867991
purpose: []
